import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/projek_20__202app/generatedframe1widget/generated/GeneratedGroup34Widget.dart';
import 'package:flutterapp/projek_20__202app/generatedframe1widget/generated/GeneratedCardHorizontalWidget2.dart';
import 'package:flutterapp/projek_20__202app/generatedframe1widget/generated/GeneratedCardHorizontalWidget3.dart';
import 'package:flutterapp/projek_20__202app/generatedframe1widget/generated/GeneratedGroup33Widget.dart';
import 'package:flutterapp/projek_20__202app/generatedframe1widget/generated/GeneratedContainerWidget.dart';
import 'package:flutterapp/projek_20__202app/generatedframe1widget/generated/GeneratedLogoWidget.dart';
import 'package:flutterapp/projek_20__202app/generatedframe1widget/generated/GeneratedCardHorizontalWidget.dart';
import 'package:flutterapp/projek_20__202app/generatedframe1widget/generated/GeneratedCardHorizontalWidget1.dart';
import 'package:flutterapp/projek_20__202app/generatedframe1widget/generated/GeneratedCardHorizontalWidget4.dart';
import 'package:flutterapp/projek_20__202app/generatedframe1widget/generated/GeneratedTransactionsWidget.dart';
import 'package:flutterapp/projek_20__202app/generatedframe1widget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/projek_20__202app/generatedframe1widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/projek_20__202app/generatedframe1widget/generated/GeneratedGroup32Widget.dart';

/* Frame Frame 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 59.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 112.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 48.0,
                child: GeneratedTransactionsWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.09420289855072464;

                  final double height =
                      constraints.maxHeight * 0.04352678571428571;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.026570048309178744,
                        y: constraints.maxHeight * 0.011160714285714286,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedLogoWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 394.0,
                height: 84.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -310.00,
                    z: 0,
                    child: GeneratedCardHorizontalWidget()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 394.0,
                height: 84.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -207.00,
                    z: 0,
                    child: GeneratedCardHorizontalWidget1()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 394.0,
                height: 84.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -110.00,
                    z: 0,
                    child: GeneratedCardHorizontalWidget2()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 394.0,
                height: 84.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -13.00,
                    z: 0,
                    child: GeneratedCardHorizontalWidget3()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 394.0,
                height: 84.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 84.00,
                    z: 0,
                    child: GeneratedCardHorizontalWidget4()),
              ),
              Positioned(
                left: -5.684341886080802e-14,
                top: 820.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 76.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 168.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 232.0,
                height: 50.0,
                child: GeneratedContainerWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.18301699357332238;

                  final double height =
                      constraints.maxHeight * 0.05095406089510236;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.16183574879227053,
                        y: constraints.maxHeight * 0.9375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup34Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 271.0,
                top: 840.0,
                right: null,
                bottom: null,
                width: 75.76903533935547,
                height: 45.65480422973633,
                child: GeneratedGroup33Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.18301699357332238;

                  final double height =
                      constraints.maxHeight * 0.05095402257783072;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.4082125603864734,
                        y: constraints.maxHeight * 0.9375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup32Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
